server:
  port:  8092

spring:
  data:
    mongodb:
      uri:  "mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.1.1"
      database: "micro"
    application:
      name: "RATING MANAGEMENT"

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8761/eureka"