server:
  port:  8091

spring:
  datasource:
    username: "root"
    password: 
    driver-class-name:  "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/bootcontact"
    name: "microservices"
  jpa:
    hibernate:
      ddl-auto: "update"
