server:
  port:  8091

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8761/eureka"

spring:
  datasource:
    username: "root"
    password: 
    driver-class-name:  "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/bootcontact"
    name: "microservices"
  jpa:
    hibernate:
      ddl-auto: "update"
  application:
    name: "USER MANAGEMENT"


